obstacle_range: 6.0
raytrace_range: 8.5

footprint: [[-0.07, -0.07], [-0.07, 0.07], [0.07, 0.07], [0.07, -0.70]]
robot_radius: 0.17

inflation_radius: 0.03
cost_scaling_factor: 1.5

map_type: costmap
# observation_sources: scan
# scan: {sensor_frame: laser, data_type: LaserScan, topic: obito/laser/scan, marking: true, clearing: true}
