local_costmap:
  global_frame: map
  robot_base_frame: robot1/base_link

  update_frequency: 1 #10.0
  publish_frequency: 1 #10.0
  transform_tolerance: 3

  static_map: false  
  rolling_window: true
  width: 0.3
  height: 0.3
  resolution: 0.003